### ISSUE TITLE
Support for other keyboards

### ISSUE THREAD

**Issue by joebonneau** [mskelton/dtsfmt#10]
Hey there,

I came across this project recently when searching for a devicetree formatter - nice work! I was wondering what it would take to support other layouts. I use a Sweep and it seems that only `kinesis:adv360` is valid for the layout field in `.dtsfmtrc.toml`.

Thanks,
Joe

**Comment by mskelton** [comment]
@joebonneau Basically it just involves adding a file to the layouts folder like this one. That defines the mapping for the keyboard.

https://github.com/mskelton/dtsfmt/blob/main/src/layouts/adv360.rs

**Comment by joebonneau** [comment]
Gotcha, seems straightforward. I don't know Rust but I do know 1s and 0s 😆 

Would you accept a PR to add a layout for the Sweep? Curious to try this out.

**Comment by mskelton** [comment]
Yeah a PR would be great
