### ISSUE TITLE
How to set format configuration

### ISSUE THREAD

**Issue by kaixa-lee** [mskelton/dtsfmt#17]
Hi, after I used this file to execute it, the format of the device tree file obtained is not the standard format. How do I need to configure it?

**Comment by mskelton** [comment]
https://github.com/mskelton/dtsfmt#config

The readme has docs.

You're issue has basically zero information, if you need help, please provide an reproducable example or links to your project. I can't help without any information.

**Comment by kaixa-lee** [comment]
ohh，thks. ▼・ᴥ・▼
